### ISSUE TITLE
Can not login with username from login popup

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#1]
I can not login with username from checkout page in the login popup on to top tight corner.

**Comment by sylvainraye** [comment]
Hi, it's a known issue. We can't at the moment find a way to overwrite the popup template in module context. However it seems possible to overwrite it into a theme. work in progress

**Comment by tinkesh-osscube** [comment]
Thanks. I am waiting for fixes.

**Comment by tinkesh-osscube** [comment]
So are you come up with a solution ?

**Comment by sylvainraye** [comment]
yes
