### ISSUE TITLE
When Username for login is disabled, trying to register

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#12]
I have disable the module but it seems that module is not disabled completely. I got below error during registration after disabling the module-

"One or more input exceptions have occurred.
username is a required field.
Username is invalid! Only letters, digits and '_-' values are accepted."

Please look into the issue. Thanks

**Comment by sylvainraye** [comment]
You cannot disable it like that. You have to run SQL queries in database to clean the new attribute "username" in different Magento tables. 

I know they finally implement a way to uninstall in a clean way a module. However just deactivating it won't help, you must uninstall it. 

If you want to uninstall the module, follow instructions here: https://github.com/diglin/Diglin_Username2/blob/master/README.md#uninstall
