### ISSUE TITLE
Can not save user from admin 

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#13]
A new user registered from frontend. When admin only try to save without entering any information, got below error-

"The value of attribute "Username" must be unique"

**Comment by tinkesh-osscube** [comment]
This is critical issue. Please fix it at a high priority. Thanks

**Comment by sylvainraye** [comment]
I'm not your free developer... Feel free to particiapte to fix issues and provide pull request. I'll update the module when I want and can.

It's written this is a beta version

**Comment by sylvainraye** [comment]
Run the following command into your database: `update  eav_attribute set is_unique = 0 where attribute_code = 'username'`
