### ISSUE TITLE
User could not save their profile from My Account

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#14]
When username attribute is not required (Changed attribute setting from database is_required => 0) and created an account without username and tried to save account info from Customer -> My Account without entering anything, got below error-

"
Fatal error: Call to a member function getValue() on null in app/code/Diglin/Username/Plugin/Model/ResourceModel/CustomerRepositoryPlugin.php on line 143"

Please resolve the issue.

**Comment by tinkesh-osscube** [comment]
Added the bellow condition in beforeSave function near line #142 . It resolved the issue
if ($usernameAttribute) {
                if ($originalUsernameAttribute) {
                    $usernameOriginal = $originalUsernameAttribute->getValue();
                }

```
        }
```

**Comment by sylvainraye** [comment]
Thanks for sharing. I fixed it in a similar way.
