### ISSUE TITLE
Username generation seems to be broking

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#2]
In the backend, when i click on the generate username button, got below error in ajax generation function-

"Error SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.entity_type_id' in 'field list', query
 was: SELECT `c`.`email`, `c`.`entity_id`, `c`.`entity_type_id`, `cev`.\* FROM `customer_entity` AS `c
`
 LEFT JOIN `customer_entity_varchar` AS `cev` ON c.entity_id = cev.entity_id WHERE (cev.entity_id NOT
 IN (1,2,3)) GROUP BY `c`.`entity_id`"

http://sitename/admin/username/username_sync/generate/section/username/key/267aaa8a7d171bc9a68c4176d102105cc139344f9390ab12e4772412f744758d/?isAjax=true

And in the username sync status, got below error-

"{"error":true,"message":"You entered an invalid Secret Key. Please refresh the page."}"

Please look into issue. Thanks

**Comment by sylvainraye** [comment]
Fixed in latest commit.
