### ISSUE TITLE
composer  require 

### ISSUE THREAD

**Issue by chrom** [diglin/Diglin_Username2#20]
Hi, i try install module:
composer  require 'diglin/module-username'                                                                                                                                      

                                                  
  [InvalidArgumentException]                      
  Could not find package diglin/module-username.  
                                                  
  Did you mean this?                              
      diglin/module-username

**Comment by sylvainraye** [comment]
Hi,

Weird, because it's on packagist https://packagist.org/packages/diglin/module-username

How looks like your current `composer.json` ?

**Comment by chrom** [comment]
requires
100.0.*|100.1.* 
but we have 101.0.2

**Comment by dmcdaniel12** [comment]
Any update here? I'm seeing the same problem.

**Comment by sylvainraye** [comment]
Hi @dmcdaniel12 

I fix the issue, the tag version was missing and packagist didn't allow to get the package. 
But be aware, this is a beta module, I didn't invested more time to test on latest Magento version and the checkout is not complete. I think I will work on it in near future as I have more experience now. 

It means you have to set the minimum-stability to least `beta` to install the package in your Magento Project.
