### ISSUE TITLE
Username case sensitive not working

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#4]
When i enable the case sensitive username from the module setting and try to login with Some letters in the upper case, i was able to logged in whereas my username was all in the lower case letters.

**Comment by sylvainraye** [comment]
which PHP version do you use?

**Comment by tinkesh-osscube** [comment]
PHP 5.6.23

**Comment by sylvainraye** [comment]
Fixed in upcoming commit
