### ISSUE TITLE
Missing login via username on the checkout page

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#5]
How can i login with my username on the checkout page when i am not logged in and want to login from checkout page? is there feature available in the current module?

**Comment by sylvainraye** [comment]
see https://github.com/diglin/Diglin_Username2/issues/1 same problem

**Comment by tinkesh-osscube** [comment]
But login popup and checkout login are different. Have a look on the attachment-
![loginpopup](https://cloud.githubusercontent.com/assets/20531370/17246413/8307c6a4-55a9-11e6-9b68-5515996b385f.png)

**Comment by sylvainraye** [comment]
yes but it is for the same reason why it doesn't work

**Comment by tinkesh-osscube** [comment]
So if the username will appear in the login popup, it will also appear on the checkout page?

**Comment by sylvainraye** [comment]
lol. Not exactly. If I find a solution for the popup, I'll find also for the checkout payment page :-)

**Comment by sylvainraye** [comment]
in this area, knockout.js is used, not a phtml file. And to overwrite such case, I don't find any information.
