### ISSUE TITLE
Username hide/show from grid

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#6]
When i save the module setting with "Display username in "Manage Customers" Grid" as disabled, i was still seeing the username in the grid regardless of the Display username in "Manage Customers" setting. However i found a solution for same as well and added the bellow piece of code in the app/code/Diglin/Username/Model/Event/ChangeEavAttribute.php to fix the issue-

"
$usedInGrid = $this->config->getValue('username/general/grid');
$attributeUsernameModel->setData('is_used_in_grid', $usedInGrid);"

**Comment by sylvainraye** [comment]
It's something which will be probably be removed from the configuration in future as you can enable/disable lots of attribute directly from the grid itself if I remember correctly.

**Comment by tinkesh-osscube** [comment]
Yes you are right, we can add/remove new columns from the grid itself but i have added the code to disable pragmatically. Thanks

**Comment by sylvainraye** [comment]
Added to code. Close for this reason. Commit coming soon
