### ISSUE TITLE
Success/Error messages are not appearing 

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#7]
When i login with invalid username/email, i cant see the error messages. The error/Success messages appears after the successful login. Kindly check the issue.

**Comment by sylvainraye** [comment]
Bug from Magento itself. As the problem appears also without the module.

**Comment by tinkesh-osscube** [comment]
I have also checked the Magento 2.1 instance without module installed and i was able to view the error/success messages but not with your module installed.

**Comment by sylvainraye** [comment]
ok I'll check again. thanks

**Comment by sylvainraye** [comment]
Cannot be reproduced. see screenshot

<img width="524" alt="capture d ecran 2016-08-11 a 02 12 39" src="https://cloud.githubusercontent.com/assets/1337461/17575398/34f3feb4-5f69-11e6-808f-7d5c56217b21.png">
