### ISSUE TITLE
Without having username for customers creating issue during login

### ISSUE THREAD

**Issue by tinkesh-osscube** [diglin/Diglin_Username2#8]
The customer those have not saved their username during registration are facing issue while login. Please have a look on the error below-

"Fatal error: Call to a member function getValue() on null in /var/www/html/js_products/migration/justbrakes-magento21/app/code/Diglin/Username/Plugin/Model/ResourceModel/CustomerRepositoryPlugin.php on line 129"

**Comment by sylvainraye** [comment]
Fixed in latest commit.
